# netlify.toml

# '/api'로 시작하는 SEC 데이터 요청을 프록시 처리합니다.
[[redirects]]
  from = "/api/*"
  to = "https://data.sec.gov/api/:splat"
  status = 200 # 200 OK 상태로 응답하여 프록시처럼 동작하게 합니다.

# '/companies-api'로 시작하는 회사 목록 요청을 프록시 처리합니다.
[[redirects]]
  from = "/companies-api/*"
  to = "https://port-0-work-fount-md5atyx32a28fa6c.sel5.cloudtype.app/:splat"
  status = 200

# '/stock-api'로 시작하는 주가 데이터 요청을 프록시 처리합니다.
[[redirects]]
  from = "/stock-api/*"
  to = "https://port-0-work-fount-md5atyx32a28fa6c.sel5.cloudtype.app/:splat"
  status = 200
