# netlify.toml 

# '/analysis-api'로 시작하는 SEC 데이터 요청을 프록시 처리합니다.
[[redirects]]
  from = "/analysis-api/*"
  to = "https://port-0-sec-viewer-backend-mddvbxmfda69479d.sel5.cloudtype.app/:splat"
  status = 200

# '/companies-api'로 시작하는 회사 목록 요청을 프록시 처리합니다.
[[redirects]]
  from = "/companies-api/*"
  to = "https://port-0-work-fount-md5atyx32a28fa6c.sel5.cloudtype.app/:splat"
  status = 200

# '/stock-api'로 시작하는 주가 데이터 요청을 프록시 처리합니다.
[[redirects]]
  from = "/stock-api/*"
  to = "https://port-0-sec-viewer-backend-mddvbxmfda69479d.sel5.cloudtype.app/:splat"
  status = 200

# '/polarityPress-api'로 시작하는 뉴스기사 요청을 프록시 처리합니다.
[[redirects]]
  from = "/polarityPress-api/*"
  to = "https://port-0-work-fount-md5atyx32a28fa6c.sel5.cloudtype.app/:splat"
  status = 200

# '/polarityPress-api'로 시작하는 뉴스기사 요청을 프록시 처리합니다.
[[redirects]]
  from = "/getNews-api/*"
  to = "https://port-0-work-fount-md5atyx32a28fa6c.sel5.cloudtype.app/:splat"
  status = 200